//Restaurant table
//get all restaurants
GET http://localhost:8000/api/restaurants

###
//get a restaurant by ID
GET http://localhost:8000/api/restaurants/8

###
//create new restaurant
POST  http://localhost:8000/api/restaurants
Content-Type: application/json

{
"city_id": 1,
  "name": "terrace villa",
  "street_address": "123 New Street",
  "Zip_code": "12345"
}

###
//update restaurant by id
PUT http://localhost:8000/api/restaurants/8
Content-Type: application/json

{
"city_id": 4,
  "name": "tamu resort",
  "street_address": "123 New Street",
  "Zip_code": "12345"
}


###
//users table
//list all users
GET http://localhost:8000/api/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgwNzY3NzZ9.FvQD7gLOBMVLfdti1xDNJSAF9MFeOY5A7T1stps50DA

###
//get user by id
GET http://localhost:8000/api/users/3

###
//create a new user
POST  http://localhost:8000/api/user

###
//update user by id
PUT http://localhost:8000/api/restaurants/8
Content-Type: application/json

{
"city_id": 4,
  "name": "tamu resort",
  "street_address": "123 New Street",
  "Zip_code": "12345"
}

###
//Citytable
//list all cities
GET http://localhost:8000/api/cities

###
//get city by id
GET http://localhost:8000/api/cities/4

###
//create new city
POST  http://localhost:8000/api/

###
//update city by id
PUT http://localhost:8000/api/

###
//menu_item table
//list all menu items
GET http://localhost:8000/api/menuitems

###
//get menu item by id
GET http://localhost:8000/api/menuitems/1

###
//create a new menu item
POST http://localhost:8000/api/menuitems

###
//update a menu item by id
PUT http://localhost:8000/api/

###
//category table
//List all categories
GET http://localhost:8000/api/categories

###
//Get a category by ID
GET http://localhost:8000/api/categories/1

###
//Create a new category
POST  http://localhost:8000/api/categories

###
//Update a category by ID
PUT   http://localhost:8000/api/categories/1


###
//state table
// List all states
GET http://localhost:8000/api/states

###
//Get a state by ID
GET http://localhost:8000/api/states/1

###
//Create a new state
POST  http://localhost:8000/api/

###
//Update a state by ID
PUT http://localhost:8000/api/


###
//address table
//List all addresses
GET http://localhost:8000/api/addresses

###
//Get an address by ID
GET http://localhost:8000/api/addresses/2

###
//Create a new address
POST  http://localhost:8000/api/

###
//Update an address by ID
PUT http://localhost:8000/api/


###
//order_menu_item table
//List all order menu items
GET http://localhost:8000/api/order_menu_items

###
//Get an order menu item by ID
GET http://localhost:8000/api/order_menu_items/1

###
//Create a new order menu item
POST  http://localhost:8000/api/

###
//Update an order menu item by ID
PUT http://localhost:8000/api/


###
//restaurant_owner table
//List all restaurant owners
GET http://localhost:8000/api/restaurant_owners

###
//Get a restaurant owner by ID
GET http://localhost:8000/api/restaurant_owners/1

###
//Create a new restaurant owner
POST  http://localhost:8000/api/

###
//Update a restaurant owner by ID
PUT http://localhost:8000/api/


###
//driver table
//List all drivers
GET http://localhost:8000/api/drivers

###
//Get a driver by ID
GET http://localhost:8000/api/drivers/1

###
//Create a new driver
POST  http://localhost:8000/api/drivers
Content-Type: application/json

{
  "car_make": "Volkswagen",
    "car_model": "civic",
    "car_year": 2020,
    "user_id": 1,
    "online": true,
    "delivering": true
}

###
//Update a driver by ID
PUT http://localhost:8000/api/


###
//orders table
// List all orders
GET http://localhost:8000/api/orders

###
//Get an order by ID
GET http://localhost:8000/api/orders/2

###
//Create a new order
POST  http://localhost:8000/api/

###
//Update an order by ID
PUT http://localhost:8000/api/


###
//order_status table
//List all order statuses
GET http://localhost:8000/api/orderstatuses

###
//Get an order status by ID
GET http://localhost:8000/api/orderstatuses/4

###
//Create a new order status
POST  http://localhost:8000/api/orderstatuses
Content-Type: application/json

{
    "order_id": 5,
    "status_catalog_id": 2    
}

###
//Update an order status by ID
PUT http://localhost:8000/api/orderstatuses/6
Content-Type: application/json

{
    "order_id": 5,
    "status_catalog_id": 3    
}


###
//status_catalog table
//List all status catalogs
GET http://localhost:8000/api/statuscatalogs

###
//Get a status catalog by ID
GET http://localhost:8000/api/statuscatalogs/1

###
//Create a new status catalog
POST  http://localhost:8000/api/

###
//Update a status catalog by ID
PUT http://localhost:8000/api/


###
//comment table
//List all comments
GET http://localhost:8000/api/comments

###
//Get a comment by ID
GET http://localhost:8000/api/comments/2

###
//Create a new comment
POST  http://localhost:8000/api/comments
Content-Type: application/json

{
    "order_id": 2,
    "user_id": 1,
    "comment_text": "delicious today finger licking",
    "is_complaint": false,
    "is_praise": true
}

###
//Update a comment by ID
PUT http://localhost:8000/api/comments/6
Content-Type: application/json

{
    "order_id": 2,
    "user_id": 1,
    "comment_text": "finger licking,,same order tomorrow",
    "is_complaint": false,
    "is_praise": true
}


###
//Authentication
//Register User
POST  http://localhost:8000/api/auth/register
Content-Type: application/json

{
"user_id": 5,
  "username": "virginia",
  "password": "password987",
  "role": "user"
}

###
//Log in
POST  http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "username": "Lonnex",
  "password": "password12345678"
}

###
// Fetch all users as an admin
GET http://localhost:8000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs
###
// Fetch a user by ID as a regular user
GET http://localhost:8000/api/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

###
//Create a new user as an admin
POST http://localhost:8000/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs


{
  "name": "Virginia wanjiru",
  "contact_phone": "123-456-7890",
  "phone_verified": true,
  "email": "virginia@gmail.com",
  "email_verified": true,
  "password": "newpassword123",
  "username": "virginia",
  "role": "user"
}

###
//Update an Existing User (Admin Only)by id
PUT http://localhost:8000/api/users/9
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs


{
 "name": "virginia wanjiru",
  "contact_phone": "123-456-7890",
  "phone_verified": true,
  "email": "virginia@gmail.com",
  "email_verified": true,
  "password": "password001",
  "username": "virginia",
  "role": "user"
}




###
//restaurants
//Fetch all restaurants (admin)
GET http://localhost:8000/api/restaurants
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs


###
//Fetch a restaurant by ID (user)
GET http://localhost:8000/api/restaurants/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

###
//Update a restaurant (admin) by id
PUT  http://localhost:8000/api/restaurants/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs

{
  "name": "Spicy Flavors",
  "street_address": "456 oak St",
  "Zip_code": "54321",
  "city_id": 3
}

###
//Create a new restaurant (admin)
POST  http://localhost:8000/api/restaurants
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs

{
  "name": "Inter Continental",
  "street_address": "187 Kenyatta AV",
  "Zip_code": "8934",
  "city_id": 1
}


###
//orders
//Fetch all orders (admin)
GET http://localhost:8000/api/orders
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs


###
//Fetch an order by ID (user)
GET http://localhost:8000/api/orders/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

###
//Update an order by id (user)
PUT  http://localhost:8000/api/orders/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

{
  "restaurant_id": 3,
  "delivery_address_id": 2,
  "user_id": 3,
  "price": 40.00,
  "discount": 10.00,
  "final_price": 30.00,
  "comment": "more cheese and more sauce"
}

###
//Create a new order (user)
POST http://localhost:8000/api/orders
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

{
  "restaurant_id": 1,
  "estimated_delivery_time": "2024-06-12T12:00:00:00Z",
  "delivery_address_id": 1,
  "user_id": 5,
  "price": 50,
  "discount": 5,
  "final_price": 45
}


###
//cities/state
//List Cities (users)
GET http://localhost:8000/api/cities
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

###
//Get City by ID (users)
GET http://localhost:8000/api/cities/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE
###
//Create a City (Admin only)
POST http://localhost:8000/api/cities
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs

{
    "name": "Chicago",
    "state_id": 1
  }

###
//Update a City by id(Admin only)
PUT http://localhost:8000/api/cities/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs

{
    "name": "LOS ANGELES",
    "state_id": 3
  }

###
//Delete a City by id (Admin only)
DELETE http://localhost:8000/api/cities/1

###
//menu item/ordermenuitem
//List menu items (user)
GET http://localhost:8000/api/menuitems
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

###
//get menu items by id (user)
GET http://localhost:8000/api/menuitems/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbWlseSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MjA1NDE5fQ.-pPDuDcTpGkzjhIuTAlZOXmWYZvUiQwQFAQ1_Q21onE

###
//create a new menu item (Admin)
POST http://localhost:8000/api/menuitems
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs

{
"name": "Pizza",
  "restaurant_id": 4,
  "category_id": 3,
  "description": "Delicious cheese pizza",
  "ingredients": "Cheese, Tomato, Dough",
  "price": 9.99,
  "active": true
}

###
//update a new menu item by id (admin)
PUT http://localhost:8000/api/menuitems/5
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMb25uZXgiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgyMDU2NTN9.OKzw_jGrkgx50mU5CAYfhX7aoa-DlwBR1fU-prEQSSs

{
"name": "Pizza",
  "restaurant_id": 4,
  "category_id": 3,
  "description": "Delicious cheese pizza",
  "ingredients": "Cheese, Tomato, Dough",
  "price": 10.99,
  "active": true
}

###
//driver/orders